tools:
    php_sim: true
    php_pdepend: true
    php_analyzer: true
filter:
    excluded_paths:
        - 'tests/*'
        - 'vendor/*'
        - 'tools/*'
build:
    environment:
        php:
            version: 5.4.28
            ini:
                'date.timezone': 'Europe/Berlin'
    dependencies:
        before:
            - "sed -i -e 's#git@github.com:#https://github.com/#g' .gitmodules"
