fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

fam_gene_tree_setup:
    path:   /setup/
    defaults:
        _controller: FrameworkBundle:Redirect:urlRedirect
        path: /app_setup.php
        permanent: false

fam_gene_tree_app:
    resource: "@FamGeneTreeAppBundle/Resources/config/routing.yml"
    prefix:   /

webtrees_legacy:
    resource: "@WebtreesLegacyBundle/Resources/config/routing.yml"
    prefix:   /

