services:
#    webtrees_legacy.example:
#        class: Webtrees\LegacyBundle\Example
#        arguments: [@service_id, "plain_value", %parameter%]

  webtrees.cache:
    class: %doctrine_cache.file_system.class%
    arguments: [ %kernel.cache_dir% ]

  webtrees.theme:
    class: Webtrees\LegacyBundle\Context\Application\Service\Theme
    arguments: [ "@fam_gene_tree_app.configuration" ]