<?php
/**
 * Created by Christoph Graupner <ch.graupner@workingdeveloper.net>.
 *
 * Copyright (c) 2015 WorkingDevelopers.NET
 */

namespace Webtrees\LegacyBundle\Context\Application\View;


use Fgt\Globals;
use Webtrees\LegacyBundle\Legacy\Filter;
use Webtrees\LegacyBundle\Legacy\I18N;
use Webtrees\LegacyBundle\Legacy\PageController;
use Webtrees\LegacyBundle\Legacy\PageControllerInterface;
use Webtrees\LegacyBundle\Legacy\Theme;

class LegacyPageController extends PageController implements PageControllerInterface
{
    protected $templateEngine;
    protected $template;

    /**
     * @param \Symfony\Bundle\TwigBundle\Debug\TimedTwigEngine $templateEngine
     * @param null|string                                      $template
     */
    public function __construct(\Symfony\Bundle\TwigBundle\Debug\TimedTwigEngine $templateEngine, $template = 'WebtreesLegacyThemeWebtreesBundle:Default:index.html.twig')
    {
        parent::__construct();
        $this->templateEngine = $templateEngine;
        $this->template       = $template;
    }

    public function pageHeader($view = '')
    {
        // Give Javascript access to some PHP constants
        $this->addInlineJavascript('
			var WT_STATIC_URL  = "' . Filter::escapeJs(WT_STATIC_URL) . '";
			var WT_MODULES_DIR = "' . Filter::escapeJs(WT_MODULES_DIR) . '";
			var WT_GEDCOM      = "' . Filter::escapeJs(WT_GEDCOM) . '";
			var WT_GED_ID      = "' . Filter::escapeJs(WT_GED_ID) . '";
			var textDirection  = "' . Filter::escapeJs(Globals::i()->TEXT_DIRECTION) . '";
			var WT_SCRIPT_NAME = "' . Filter::escapeJs(WT_SCRIPT_NAME) . '";
			var WT_LOCALE      = "' . Filter::escapeJs(WT_LOCALE) . '";
			var WT_CSRF_TOKEN  = "' . Filter::escapeJs(Filter::getCsrfToken()) . '";
		', self::JS_PRIORITY_HIGH);

        // Temporary fix for access to main menu hover elements on android/blackberry touch devices
        $this->addInlineJavascript('
			if(navigator.userAgent.match(/Android|PlayBook/i)) {
				jQuery(".primary-menu > li > a").attr("href", "#");
			}
		');

        echo $this->getTemplateEngine()->render(
            'WebtreesLegacyThemeBundle:Default:index.html.twig',
            array(
                'html_markup'               => I18N::html_markup(),
                'head_contents'             => Theme::theme()->headContents($this),
                'hook_header_extra_content' => Theme::theme()->hookHeaderExtraContent(),
                'body_header'               => $view == 'simple'
                    ? Theme::theme()->bodyHeaderPopupWindow()
                    : Theme::theme()->bodyHeader(),
                'analytics'                 => Theme::theme()->analytics(),
                'page_title'                => $this->getPageTitle(),
                'metaRobots'                => $this->getMetaRobots(),
                'canonicalUrl'              => $this->getCanonicalUrl(),
                'inline_javascript'          => $this->getJavascript()
            )
        );

        // We've displayed the header - display the footer automatically
        $this->page_header = true;

        return $this;
    }

    protected function pageFooter()
    {
        return parent::pageFooter(); // TODO: Change the autogenerated stub
    }

    /**
     * @return \Symfony\Bundle\TwigBundle\Debug\TimedTwigEngine
     */
    public function getTemplateEngine()
    {
        return $this->templateEngine;
    }


}