fam_gene_tree_app_homepage:
    path:     /hello/{name}
    defaults: { _controller: FamGeneTreeAppBundle:Default:index }

_fgt_login:
    path:   /auth/login
    defaults: { _controller: FamGeneTreeAppBundle:Auth:login }

_fgt_logout:
    path:   /auth/logout
    defaults: { _controller: FamGeneTreeAppBundle:Auth:logout }