services:
#    fam_gene_tree_app.example:
#        class: FamGeneTree\AppBundle\Example
#        arguments: [@service_id, "plain_value", %parameter%]

  fgt.configuration.factory:
    class: FamGeneTree\AppBundle\Context\Configuration\Infrastructure\ConfigRepository
    arguments: [@service_container]

  fgt.configuration:
    class: FamGeneTree\AppBundle\Context\Configuration\Domain\FgtConfig
    factory: ["@fgt.configuration.factory", load]

  fgt.tblprefix_subscriber:
    class: FamGeneTree\AppBundle\Subscriber\TablePrefixSubscriber
    arguments: [%database_prefix%]
    tags:
      - { name: doctrine.event_subscriber }

  fgt.session:
    class: FamGeneTree\AppBundle\Service\Session
    arguments: [@service_container]

  fgt.auth:
    class: FamGeneTree\AppBundle\Service\Auth
    arguments: [@service_container]
