services:
#    fam_gene_tree_setup.example:
#        class: FamGeneTree\SetupBundle\Example
#        arguments: [@service_id, "plain_value", %parameter%]
  fgt.configuration.setup:
    class: FamGeneTree\AppBundle\Context\Configuration\Domain\FgtConfig
    factory: ["@fgt.configuration.factory", loadSetupConfig]

  fgt.setup.manager:
    class: FamGeneTree\SetupBundle\Context\Setup\SetupManager
    arguments: [@service_container]

  fgt.setup.prerequirementsfactory:
    class: FamGeneTree\SetupBundle\Context\Setup\Step\PreRequirementsFactory
    arguments: [@service_container]

  fgt.setup.service.step.database:
    class: FamGeneTree\SetupBundle\Context\Setup\Step\DatabaseSetup
    arguments: [@service_container]