services:
  fgt.setup.configuration.factory:
    class: FamGeneTree\AppBundle\Context\Configuration\Infrastructure\ConfigRepository
    arguments: [@service_container]

  fgt.setup.configuration:
    class: FamGeneTree\AppBundle\Context\Configuration\Domain\FgtConfig
    factory: ["@fgt.setup.configuration.factory", loadSetupConfig]

  fgt.setup.configuration.parameters.factory:
    class: FamGeneTree\AppBundle\Context\Configuration\Infrastructure\ParametersRepository
    arguments: [@service_container]

  fgt.setup.configuration.parameters:
    class: FamGeneTree\AppBundle\Context\Configuration\Domain\SymfonyParameters\SymfonyParameters
    factory: ["@fgt.setup.configuration.parameters.factory", load]

  fgt.setup.manager:
    class: FamGeneTree\SetupBundle\Context\Setup\SetupManager
    arguments: [@service_container]

  fgt.setup.prerequirementsfactory:
    class: FamGeneTree\SetupBundle\Context\Setup\Step\PreRequirementsStep
    arguments: [@service_container]

  fgt.setup.service.step.database:
    class: FamGeneTree\SetupBundle\Context\Setup\Step\DatabaseSettingsStep
    arguments: [@service_container]

  fgt.setup.service.step.database.creation:
    class: FamGeneTree\SetupBundle\Context\Setup\Step\DatabaseCreationStep
    arguments: [@service_container]

  fgt.setup.service.step.first_settings:
    class: FamGeneTree\SetupBundle\Context\Setup\Step\FirstSettingsStep
    arguments: [@service_container]

  fgt.migrate.service:
    class: FamGeneTree\SetupBundle\Context\Migration\Service\Migrate
    arguments: [@service_container]
